# Generated by Django 6.0.3 on 2026-03-28 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_token', models.CharField(max_length=255, unique=True)),
                ('model_id', models.CharField(max_length=255)),
                ('model_label', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=20)),
                ('language', models.CharField(default='en', max_length=20)),
                ('video_style', models.CharField(blank=True, max_length=20)),
                ('video_orientation', models.CharField(blank=True, max_length=20)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('used_reference_images', models.BooleanField(default=False)),
                ('guidance_note', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_description', models.TextField(blank=True)),
                ('assets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
