# Generated by Django 6.0.3 on 2026-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrecord',
            name='pipeline_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationrecord',
            name='pipeline_stage',
            field=models.CharField(choices=[('provider', 'Provider'), ('starter_frame', 'Starter Frame'), ('video_render', 'Video Render')], default='provider', max_length=30),
        ),
        migrations.AddField(
            model_name='generationrecord',
            name='provider_request_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
